<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RadioTEDU-OnAir-Supervisor</AssemblyName>
    <ApplicationIcon>../../../app/static/icons/icon.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>CleanroomRadio.ServiceHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="service-host-template.services" CopyToOutputDirectory="PreserveNewest" />
    <None Include="README.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
